export enum StringTemplates {
  EmailTaskName = 'PSChannelExperienceEmailTaskName',
  FaxTaskName = 'PSChannelExperienceFaxTaskName',
  WebformTaskName = 'PSChannelExperienceWebformTaskName',
  MessengerTaskName = 'PSChannelExperienceMessengerTaskName',
  FaxInfoHeading = 'PSChannelExperienceFaxInfoHeading',
  FaxInfoDepartment = 'PSChannelExperienceFaxInfoDepartment',
  FaxInfoFrom = 'PSChannelExperienceFaxInfoFrom',
  FaxInfoReceived = 'PSChannelExperienceFaxInfoReceived',
  FaxInfoChannel = 'PSChannelExperienceFaxInfoChannel',
  FaxInfoChannelPath = 'PSChannelExperienceFaxInfoChannelPath',
  FaxInfoViewDocument = 'PSChannelExperienceFaxInfoViewDocument',
  WebformInfoHeading = 'PSChannelExperienceWebformInfoHeading',
  WebformInfoType = 'PSChannelExperienceWebformInfoType',
  WebformInfoSubmittedBy = 'PSChannelExperienceWebformInfoSubmittedBy',
  WebformInfoReceived = 'PSChannelExperienceWebformInfoReceived',
  WebformInfoViewDetails = 'PSChannelExperienceWebformInfoViewDetails',
  MessengerPrefix = 'PSChannelExperienceMessengerPrefix',
}

export const stringHook = () => ({
  'en-US': {
    [StringTemplates.EmailTaskName]: 'Email',
    [StringTemplates.FaxTaskName]: 'Fax',
    [StringTemplates.WebformTaskName]: 'Webform',
    [StringTemplates.MessengerTaskName]: 'FB Messenger',
    [StringTemplates.FaxInfoHeading]: 'Inbound Fax',
    [StringTemplates.FaxInfoDepartment]: 'Department',
    [StringTemplates.FaxInfoFrom]: 'From',
    [StringTemplates.FaxInfoReceived]: 'Received',
    [StringTemplates.FaxInfoChannel]: 'Channel',
    [StringTemplates.FaxInfoChannelPath]: 'Sinch Fax → Email → Flex',
    [StringTemplates.FaxInfoViewDocument]: 'View Fax Document',
    [StringTemplates.WebformInfoHeading]: 'Form Submission',
    [StringTemplates.WebformInfoType]: 'Type',
    [StringTemplates.WebformInfoSubmittedBy]: 'Submitted By',
    [StringTemplates.WebformInfoReceived]: 'Received',
    [StringTemplates.WebformInfoViewDetails]: 'View Form Details',
    [StringTemplates.MessengerPrefix]: 'FB Messenger',
  },
});
